# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/

# url: "http://yourdomain.com" # the base hostname & protocol for your site
host: "ouinon.github.io" # the base hostname & protocol for your site
url: "http://ouinon.github.io" # the base hostname & protocol for your site
hoststring: "ouinon.github.io" # the base hostname & protocol for your site

twitter_link: "https://twitter.com/ouinonco"
github_link: "https://github.com/ouinon"
linkedin_link: "https://www.linkedin.com/in/robertstarbuck"

highlighter: pygments

# Build settings
paginate_path: '/page/:num'
paginate: 5
markdown: kramdown
permalink: /:categories/:title
collections:
  pages:
    output: true
# source: pages

defaults:
  -
    values:
      fillcolour: "#009a66"
      fillcolourB: "#99d5bc"
      fillfooter: "#99d5bc"
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts