# Site settings
title: OuiNon - 
email: robert@ouinon.co
description: > # A blog about front-end web development.
baseurl: "" # the subpath of your site, e.g. /blog/

# url: "http://yourdomain.com" # the base hostname & protocol for your site
host: "local.ouinon.co" # the base hostname & protocol for your site
url: "http://blog.ouinon.co/" # the base hostname & protocol for your site
hoststring: "blog.ouinon.co" # the base hostname & protocol for your site

twitter_link: "https://twitter.com/ouinonco"
github_link: "https://github.com/ouinon"
linkedin_link: "https://www.linkedin.com/in/robertstarbuck"
exclude: ['blog-ouinon.sublime-project']
highlighter: pygments

# Build settings
paginate_path: '/page/:num'
paginate: 5
markdown: kramdown
permalink: /:categories/:title
collections:
  pages:
    output: true
# source: pages

defaults:
  -
    values:
      fillcolour: "#009a66"
      fillcolourB: "#99d5bc"
      fillfooter: "#99d5bc"
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts